version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: doc
          command: npm run docs
  publish-github-release:
    filters:
      branches:
        only: master
      tags:
        only: /^v\d+\.\d+\.\d+$/
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
        at: ./artifacts
      - run:
        name: "Publish Release on GitHub"
        command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r
            ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERS